### ISSUE TITLE
Sound toggles in NavigationFragment are not working properly

### ISSUE THREAD

**Issue by mohand1993** [Sygic/sygic-maps-kit-android#103]
When turning off sounds in NavigationFragment only the instructions are being muted, but the tones are still on.

**Reproduction steps:**
- Start one of the NavigationSamples (e.g. Navigation - Preview enabled)
- Start preview
- Click on the left Button on the InfoBar, and select "Sounds off"
- Navigation-Instructions announcement are turned off but there still a tone audible

**Comment by Darxie** [comment]
Hello, 
This issue has been fixed in SygicMapsSDK v15.8.0 (https://www.sygic.com/sk/developers/sygic-maps-sdk/release-notes/15-8-0/change-log)
