### ISSUE TITLE
Unable to build the project.

### ISSUE THREAD

**Issue by deveshmittal** [Sygic/sygic-maps-kit-android#109]
Hi, 
I'm unable to build the project even with the correct key provided!

Could not determine the dependencies of task ':app-samples:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app-samples:debugCompileClasspath'.
   > Could not find com.sygic.sdk:maps-android:15.0.4.
     Required by:
         project :app-samples > project :module-browsemap > project :module-common > project :uikit-viewmodels

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Has the maps-android version 15.0.4 been deployed?

**Comment by Darxie** [comment]
Hello, could you please try this branch? https://github.com/Sygic/sygic-maps-kit-android/tree/integration/15.9.6

**Comment by Darxie** [comment]
I am closing this issue due to prolonged inactivity.
