### ISSUE TITLE
Allow users to move things.

### ISSUE THREAD

**Issue by lukapaluka8** [Sygic/sygic-maps-kit-android#96]
I don't know if I'm allowed to post stuff here, but I am wanting to use the beta for the traffic lights in the US, but it blocks the lane guidance when they are open at the same time. Please allow me to either move the lane guidance or the traffic light countdown please.

**Comment by bio007** [comment]
You are allowed to write here but this issue is not related to this project ;)

What you want is a help with 	
Sygic GPS Navigation & Maps app and for that contact support@sygic.zendesk.com please.
